### ISSUE TITLE
Stuck Night Club

### ISSUE THREAD

**Issue by zoiodelula** [bruno1308/thecrimshelper#1]
Iam getting stuck when going to stamine
![sem titulo](https://user-images.githubusercontent.com/32249257/30787402-e39857f8-a15d-11e7-9e12-34cab8354e5d.jpg)

**Comment by bruno1308** [comment]
Hmm.. I'll take a look into it, I never imagined someone would actually use this

**Comment by zoiodelula** [comment]
Speak Portuguese:



2017-10-02 19:06 GMT-03:00 Bruno <notifications@github.com>:

**Comment by bruno1308** [comment]
Sim!
Aqui tá funcionando ainda... Qual nightclub está marcada como sua favorita? Talvez tenha algum caracter estranho no nome do nightclub (acentos, etc..) e ele esteja quebrando por causa disso
![image](https://user-images.githubusercontent.com/8274038/31157275-0b4973d4-a890-11e7-9d93-22722d6d767b.png)

**Comment by bruno1308** [comment]
Poderia testar com a última mudança que fiz? Acredito que resolve o problema

**Comment by zoiodelula** [comment]
Sim eu testo, mais este round perdi a conta vou esperar o proximo, viu
tenta rodar ele um tempo e veja se voce toma ban. Caso nao tome acredito
que uma melhoria seria a de aceitar os roubos de gang quando possivel

2017-10-03 23:30 GMT-03:00 Bruno <notifications@github.com>:
